### ISSUE TITLE
Create example on planette

### ISSUE THREAD

**Issue by f3l1x** [contributte/translation#12]
It would be great to have a working example on https://github.com/contributte/playground repo.

**Comment by f3l1x** [comment]
Could you please take a look @aleswita?

**Comment by TomasHalasz** [comment]
I've issue with translation of text with spaces. For example `$translator->translate('Kočka leze dírou, pes oknem');`  is looking for string "Kočka leze dírou, pes oknem" in default messages.local.neon even if I hade set different domain by `$translator->setPrefix(['customModule.status']); `  I don't know if it is error or behavior by design. 

My idea is to replace spaces with underscores in messages, because it's still readable in case of missing translate in neon. 
And the best way in my opinion is in Translator.php :

```
public function translate($message, ...$parameters): string // @comment

{

        $message = str_ireplace(" ","_",$message);


```



Nice would be if user can set on or off this replacing space by underscore. What do you think?

**Comment by f3l1x** [comment]
Ping :-)

**Comment by petrparolek** [comment]
Pong
