### ISSUE TITLE
Translating doesnt work with symfony/translation v5.3.4 (v5.3.3 is OK)

### ISSUE THREAD

**Issue by BigOHenry** [contributte/translation#73]
PHP 7.4
contributte/translation: 0.9.2

Translating doesnt work with symfony/translation v5.3.4, but with v5.3.3 is OK
Tried also contributte/translation 0.8.2 and 0.8.3 and same result. Instead of translated text it display translation string.

**Comment by zraly** [comment]
I have the same problem. Maybe it is related to bug #42068 (https://github.com/symfony/translation/releases/tag/v5.3.4), because, when I updated to 5.3.4, `en_US_POSIX` appeared in debugger bar instead of `cz_CZ` and the translation was alway english. The locale string was still `cz_CZ`.

**Comment by Gappa** [comment]
Yup, same here. I've tried to fiddle with it and the problem seems to be in `Translator.php`:

- https://github.com/symfony/translation/commit/c1cca3eb086bb62d98890631ef6bbc65ce913dd1#diff-aa236a1ac1f79a40df8a2b068e08e756bcc1e3523750be4ff91059a83394c859

Somebody in the comments mentions the same problem:

- https://github.com/symfony/translation/commit/c1cca3eb086bb62d98890631ef6bbc65ce913dd1#commitcomment-54056098

So, unless this gets fixed in Symfony/Translation, the only workaround is to limit the version to 5.3.3.

**Comment by sasule** [comment]
Very stupid workaround but works:
```
$locale = $this->translator->getLocaleResolver()->resolve($this->translator);
if ($this->translator->getLocale() !== $locale) {
	//not set or EN_US_POSIX
	$this->translator->setLocale($locale);
}
```
This "fixes" initial setting of locale. Change of locale later in code eg. via handleSetLocale (from dokumentation) is not affected.

**Comment by aleswita** [comment]
Can you try ` init_lang` branch?

**Comment by sasule** [comment]
> Can you try ` init_lang` branch?

Maybe later this day on my private project. I can't try it on running public projects.

**Comment by spaze** [comment]
> Can you try ` init_lang` branch?

Can confirm [the change](https://github.com/contributte/translation/commit/6e16371c150a33f4fafc5a44c51b986101206e9e#diff-eacdee021952408874fa89f5f706adcbc864deb46dc1b18bfb042beaad944b85) fixed the issue reported here for me.

**Comment by spaze** [comment]
Also setting `intl.default_locale` in `php.ini` fixes the issue. (Maybe only when ext/intl is loaded)

**Comment by aleswita** [comment]
Fixed by https://github.com/contributte/translation/commit/8565552a02508da4eea0ae330432356a07fc5f43
